all:
	g++ -c -o ./leftpad/test_builds/leftpad.o ./leftpad/LeftPad.cpp
	g++ -o ./leftpad/test_builds/leftpad ./leftpad/test_builds/leftpad.o
	./leftpad/test_builds/leftpad
#
#ifeq ($(OS), Windows_NT)
#	cls
#else
#	clear
#endif